### ISSUE TITLE
Imgui fails to compile

### ISSUE THREAD

**Issue by Vawx** [IainWinter/IwEngine#2]
It looks like the wEngine project doesn't have a good reference to imgui, causing a bunch of missed types.

I don't know enough about how your project is setup to fix this on my own. Any help is appreciated.

**Comment by Vawx** [comment]
I was able to get ImGui fixed. I had to pull down the specific CL from the fork you have for imgui.

I am now having trouble getting any game project to load.

**Comment by IainWinter** [comment]
Hey sorry for the late reply, github doesn't send a notification about issues?? My biggest gripe with dev rn are these libraries so it might be setup wrong I'm not too sure. Did you follow the directions in the readme? Because I've done that on a fresh laptop and it works so I'm not sure what you ran into

What do you mean load? With the editor? or getting a game to link to the engine?

**Comment by IainWinter** [comment]
Yeah that was something a little annoying about using the 'editor', I was playing around with loading the projects as dlls so the editor could be separate. The idea being that in future I should be able to recompile the game without closing the editor. 

So you need to edit the `premake5.lua` file in `./Games` to compile a dll, I just changed it so now now there are two vars at the top of the file so it's ezpz...

I just updated the editor so it should all be in working order now. Let me know if it still doesn't work.

I tried to run the PhysicsProject code again, but for some reason its paused and the lightning is broken. I'll put a lil time in tomorrow to see if I can fix that up.

**Comment by Vawx** [comment]
Awesome. Thank you for putting in time to help me out. I appreciate it.
